[package]
name = "gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.2.1", package = "libadwaita", features = ["gtk_v4_6"] }
gtk = { version = "0.5.5", package = "gtk4", features = ["v4_8"] }
text-engine = { path = "../../engine" }
